name: Generate and upload a release assets

on: push
  # release:
  #   types:
  #     - published
  #     # - unpublished
  #     - created
  #     - edited
  #     #- deleted
  #     - prereleased
  #     - released

jobs:
  upload:
    name: Upload Artifacts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: Zeek-Transport/shell-lib/docker/install_docker.sh
      - run: Zeek-Transport/installer/generate_installer.sh
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Zeek-Transport/installer/Zeek-Transport.tar